const lingua = {};

lingua['home-title-PT'] = 'Bem vindo!'
lingua['home-title-PT-BR'] = 'Bem vindo!'
lingua['home-title-EN'] = 'Welcome!'
lingua['home-subtitle-PT'] = "Sistema de Gestão Escolar"
lingua['home-subtitle-PT-BR'] = "Sistema de Gestão Escolar"
lingua['home-subtitle-EN'] = "School's management system"
lingua['home-option-EN'] = 'Select a language'
lingua['home-option-PT-BR'] = 'Selecione a linguagem'
lingua['home-option-PT'] = 'Selecione o idioma'
lingua['home-content-PT'] = 'Sistema para gerenciamento escolar desenvolvido para a disciplina de Gestão de Projetos B!'
lingua['home-content-PT-BR'] = 'Sistema de gerenciamento escolar desenvolvido para a disciplina Gestão de Projetos B!'
lingua['home-content-EN'] = "System for school's management developed for the subject Management of Projects B!"
lingua['school-title-PT'] = "Escolas"
lingua['school-title-PT-BR'] = "Escolas"
lingua['school-title-EN'] = "Schools"
lingua['school-subtitle-PT'] = "Registrar nova escola"
lingua['school-subtitle-PT-BR'] = "Cadastrar nova escola"
lingua['school-subtitle-EN'] = "Register new school"
lingua['labelname-PT'] = "Nome:"
lingua['labelname-PT-BR'] = "Nome:"
lingua['labelname-EN'] = "Name:"
lingua['labelsurname-PT'] = "Sobrenome:"
lingua['labelsurname-PT-BR'] = "Sobrenome:"
lingua['labelsurname-EN'] = "Surname:"
lingua['labeladdress-PT'] = "Endereço:"
lingua['labeladdress-PT-BR'] = "Endereço:"
lingua['labeladdress-EN'] = "Address:"
lingua['labelphone-PT'] = "Telefone:"
lingua['labelphone-PT-BR'] = "Telefone:"
lingua['labelphone-EN'] = "Telephone:"
lingua['labelTypeBusiness-PT'] = "Empresa"
lingua['labelTypeBusiness-PT-BR'] = "Empresa"
lingua['labelTypeBusiness-EN'] = "Business"
lingua['labelTypePersonal-PT'] = "Pessoal"
lingua['labelTypePersonal-PT-BR'] = "Pessoal"
lingua['labelTypePersonal-EN'] = "Personal"
lingua['labelstudents-PT'] = "Alunos"
lingua['labelstudents-PT-BR'] = "Alunos"
lingua['labelstudents-EN'] = "Students"
lingua['labelstudent-PT'] = "Aluno"
lingua['labelstudent-PT-BR'] = "Aluno"
lingua['labelstudent-EN'] = "Student"
lingua['school-labelprincipal-PT'] = "Director:"
lingua['school-labelprincipal-PT-BR'] = "Diretor:"
lingua['school-labelprincipal-EN'] = "Principal:"
lingua['labelCPF-PT'] = "NIF"
lingua['labelCPF-PT-BR'] = "CPF"
lingua['labelCPF-EN'] = "Social security number"
lingua['holderCPF-PT'] = "Digite o NIF"
lingua['holderCPF-PT-BR'] = "Digite o CPF"
lingua['holderCPF-EN'] = "Type the Social security number"
lingua['labelbirthdate-PT'] = "data de nascimento:"
lingua['labelbirthdate-PT-BR'] = "data de nascimento:"
lingua['labelbirthdate-EN'] = "Birth date:"
lingua['name-PT'] = "Digite o nome"
lingua['name-PT-BR'] = "Digite o nome"
lingua['name-EN'] = "Type the name"
lingua['surname-PT'] = "Digite o sobrenome"
lingua['surname-PT-BR'] = "Digite o sobrenome"
lingua['surname-EN'] = "Type the surname"
lingua['address-PT'] = "Digite o endereço"
lingua['address-PT-BR'] = "Digite o endereço"
lingua['address-EN'] = "Type the address"
lingua['telephone-PT'] = "Digite o telefone da escola"
lingua['telephone-PT-BR'] = "Digite o telefone da escola"
lingua['telephone-EN'] = "Type the telephone"
lingua['cpf-PT'] = "Escrevas o CPF aqui"
lingua['cpf-PT-BR'] = "Escreva o CPF aqui"
lingua['cpf-EN'] = "Type the CPF here"
lingua['email-PT'] =  "Digite o E-mail:"
lingua['email-PT-BR'] = "Digite o E-mail:"
lingua['email-EN'] = "Type the E-mail:"
lingua['option-PT'] = "Selecione uma opção:"
lingua['option-PT-BR'] = "Escolha uma opção:"
lingua['option-EN'] = "Select an option:"
lingua['password-PT'] = "Digites uma senha"
lingua['password-PT-BR'] = "Digite uma senha"
lingua['password-EN'] = "Type a password"
lingua['buttonsave-PT'] = "Salvar"
lingua['buttonsave-PT-BR'] = "Salvar"
lingua['buttonsave-EN'] = "Save"
lingua['buttoncancel-PT'] = "Cancelar"
lingua['buttoncancel-PT-BR'] = "Cancelar"
lingua['buttoncancel-EN'] = "Cancel"

// Form Tables

lingua['table-name-PT'] = "Nome"
lingua['table-name-PT-BR'] = "Nome"
lingua['table-name-EN'] = "Name"
lingua['table-surname-PT'] = "Sobrenome"
lingua['table-surname-PT-BR'] = "Sobrenome"
lingua['table-surname-EN'] = "Surname"
lingua['table-address-PT'] = "Endereço"
lingua['table-address-PT-BR'] = "Endereço"
lingua['table-address-EN'] = "Address"
lingua['table-telephone-PT'] = "Telefone"
lingua['table-telephone-PT-BR'] = "Telefone"
lingua['table-telephone-EN'] = "Telephone"
lingua['table-birthdate-PT'] = "Data de nascimento"
lingua['table-birthdate-PT-BR'] = "Data de nascimento"
lingua['table-birthdate-EN'] = "Birth date"
lingua['table-principal-PT'] = "Director"
lingua['table-principal-PT-BR'] = "Diretor"
lingua['table-principal-EN'] = "Principal"
lingua['table-password-PT'] = "Senha"
lingua['table-password-PT-BR'] = "Senha"
lingua['table-password-EN'] = "Password"
lingua['table-alter-PT'] = "Alterar"
lingua['table-alter-PT-BR'] = "Alterar"
lingua['table-alter-EN'] = "Alter"
lingua['table-remove-PT'] = "Remover"
lingua['table-remove-PT-BR'] = "Remover"
lingua['table-remove-EN'] = "Remove"
lingua['table-guardianName-PT'] = "Nome do responsável"
lingua['table-guardianName-PT-BR'] = "Nome do responsável"
lingua['table-guardianName-EN'] = "Guardian name"
lingua['table-guardianEmail-PT'] = "Email do responsável"
lingua['table-guardianEmail-PT-BR'] = "Email do responsável"
lingua['table-guardianEmail-EN'] = "Guardian's email"
lingua['table-guardianPass-PT'] = "Senha do responsável"
lingua['table-guardianPass-PT-BR'] = "Senha do responsável"
lingua['table-guardianPass-EN'] = "Guardian pass"


// Alertas

lingua['telephone-message-PT'] = "Tu deves preencher os dados de telefone no padrão: '+55 (55) 23321-5454'"
lingua['telephone-message-PT-BR'] = "Você deve preencher os dados de telefone no padrão: '+55 (55) 23321-5454'"
lingua['telephone-message-EN'] = "You must type the telephone in the format: '+55 (55) 23321-5454' "
lingua['date-message-PT'] = "Tu deves inserir uma data menor que a atual"
lingua['date-message-PT-BR'] = "Você deve inserir uma data menor que a atual"
lingua['date-message-EN'] = "You must choose a older date than today's"
lingua['cpf-message-PT'] = "Tu deves preencher os dados de CPF no padrão: '123.456.789-00'"
lingua['cpf-message-PT-BR'] = "Você deve preencher os dados de CPF no padrão: '123.456.789-00'"
lingua['cpf-message-EN'] = "You must fill the CPF field in the formart: '123.456.789-00'"
lingua['email-message-PT'] = "Tu deves preencher os dados de E-mail no padrão: 'teste09@puccampinas.com'"
lingua['email-message-PT-BR'] = "Você deve preencher os dados de E-mail no padrão: 'teste09@puccampinas.com'"
lingua['email-message-EN'] = "You must fill the E-mail field in the format: 'teste09@puccampinas.com'"
lingua['save-message-PT'] = "Tu deves preencher os dados para poder salvar"
lingua['save-message-PT-BR'] = "Você deve preencher os dados para poder salvar"
lingua['save-message-EN'] = "You need to input the data in order to save"
lingua['save-success-PT'] = "Registro feito com sucesso!"
lingua['save-success-PT-BR'] = "Inserção feita com sucesso!"
lingua['save-success-EN'] = "Successlly register"

// Aluno
lingua['student-title-PT'] = "Alunos"
lingua['student-title-PT-BR'] = "Alunos"
lingua['student-title-EN'] = "Students"
lingua['student-subtitle-PT'] = "Registrar novo aluno"
lingua['student-subtitle-PT-BR'] = "Cadastrar novo aluno"
lingua['student-subtitle-EN'] = "Register new student"

lingua['holderName-PT'] = "Carlitos"
lingua['holderName-PT-BR'] = "Carlos"
lingua['holderName-EN'] = "Carl"
lingua['holderSurname-PT'] = "Lima"
lingua['holderSurname-PT-BR'] = "Ramos"
lingua['holderSurname-EN'] = "Ander"
lingua['holderEmail-PT'] = "email@email.com"
lingua['holderEmail-PT-BR'] = "email@email.com"
lingua['holderEmail-EN'] = "email@email.com"
lingua['holderAddress-PT'] = "Rua das flores, 335"
lingua['holderAddress-PT-BR'] = "Rua das flores, 335"
lingua['holderAddress-EN'] = "Flower Avenue, 550"
lingua['holderPhone-PT'] = "+55 (55) 23321-5454"
lingua['holderPhone-PT-BR'] = "+55 (55) 23321-5454"
lingua['holderPhone-EN'] = "+55 (55) 23321-5454"

lingua['labelguardianname-PT'] = "Nome do responsavel:"
lingua['labelguardianname-PT-BR'] = "Nome do responsavel:"
lingua['labelguardianname-EN'] = "Name of legal guardian:"
lingua['holderGuardianName-PT'] = "Digite o nome do responsavel do aluno"
lingua['holderGuardianName-PT-BR'] = "Digite o nome do responsavel do aluno"
lingua['holderGuardianName-EN'] = "Type the student guardian name"
lingua['holderStudentGuardianEmail-PT'] = "Digite o email do responsável"
lingua['holderStudentGuardianEmail-PT-BR'] = "Digite o email do responsável"
lingua['holderStudentGuardianEmail-EN'] = "Type the student guardian email"
lingua['holderStudentGuardianPass-PT'] = "Crie uma senha para o responsável"
lingua['holderStudentGuardianPass-PT-BR'] = "Crie uma senha para o responsável"
lingua['holderStudentGuardianPass-EN'] = "Create a password for the guardian"

lingua['labelguardianemail-PT'] = "E-mail do responsavel:"
lingua['labelguardianemail-PT-BR'] = "E-mail do responsvel:"
lingua['labelguardianemail-EN'] = "Legal guardian's Email:"
lingua['labelguardianpass-PT'] = "Senha do responsavel:"
lingua['labelguardianpass-PT-BR'] = "Senha do responsavel:"
lingua['labelguardianpass-EN'] = "Legal guardian's password"

// Nav
lingua['nav-school-PT'] = "Escolas"
lingua['nav-school-PT-BR'] = "Escolas"
lingua['nav-school-EN'] = "Schools"
lingua['nav-students-PT'] = "Alunos"
lingua['nav-students-PT-BR']  = "Alunos"
lingua['nav-students-EN'] = "Students"

lingua['nav-directors-PT'] = "Diretores"
lingua['nav-directors-PT-BR'] = "Diretores"
lingua['nav-directors-EN'] = "Directors"

lingua['nav-teachers-PT'] = "Professores"
lingua['nav-teachers-PT-BR']= "Professores"
lingua['nav-teachers-EN'] = "Teachers"

lingua['nav-administrators-PT'] = "Administradores"
lingua['nav-administrators-PT-BR'] = "Administradores"
lingua['nav-administrators-EN'] = "Administrators"

lingua['nav-subjects-PT'] = "Matérias"
lingua['nav-subjects-PT-BR'] = "Matérias"
lingua['nav-subjects-EN'] = "School subjects"

lingua['nav-occurences-PT'] = "Ocorrências"
lingua['nav-occurences-PT-BR'] = "Ocorrências"
lingua['nav-occurences-EN'] = "Occurences"

lingua['nav-grades-PT'] = "Notas"
lingua['nav-grades-PT-BR'] = "Notas"
lingua['nav-grades-EN'] = "Grades"

// Diretor
lingua['director-title-PT'] = "Ditores"
lingua['director-title-PT-BR'] = "Diretores"
lingua['director-title-EN'] = "Directors"
lingua['director-subtitle-PT'] = "Registrar novo diretor"
lingua['director-subtitle-PT-BR'] = "Cadastrar novo diretor"
lingua['director-subtitle-EN'] = "Register new director"

// Professor
lingua['teacher-title-PT'] = "Professores"
lingua['teacher-title-PT-BR'] = "Professores"
lingua['teacher-title-EN'] = "Teachers"
lingua['teacher-subtitle-PT'] = "Registrar novo professor"
lingua['teacher-subtitle-PT-BR'] = "Cadastrar novo professor"
lingua['teacher-subtitle-EN'] = "Register new teacher"

lingua['labelteacher-PT'] = "Professor"
lingua['labelteacher-PT-BR'] = "Professor"
lingua['labelteacher-EN'] = "Teacher"


// Administrador
lingua['administrator-title-PT'] = "Administradores"
lingua['administrator-title-PT-BR'] = "Administradores"
lingua['administrator-title-EN'] = "Administrator"
lingua['administrator-subtitle-PT'] = "Registrar novo adm"
lingua['administrator-subtitle-PT-BR'] = "Cadastrar novo adm"
lingua['administrator-subtitle-EN'] = "Register new administrator"

// Materias
lingua['subjects-title-PT'] = "Matérias"
lingua['subjects-title-PT-BR'] = "Matérias"
lingua['subjects-title-EN'] = "Subjects"
lingua['subjects-subtitle-PT'] = "Registrar nova matéria"
lingua['subjects-subtitle-PT-BR'] = "Cadastrar nova matéria"
lingua['subjects-subtitle-EN'] = "Register new subject"

lingua['holderSubject-PT'] = "Inglês"
lingua['holderSubject-PT-BR'] = "Inglês"
lingua['holderSubject-EN'] = "Math"

lingua['selectChooseTeacher-PT'] = "Selecione um professor"
lingua['selectChooseTeacher-PT-BR'] = "Selecione um professor"
lingua['selectChooseTeacher-EN'] = "Choose a teacher"

lingua['selectChooseStudents-PT'] = "Selecione os alunos dessa materia"
lingua['selectChooseStudents-PT-BR'] = "Selecione os alunos dessa materia"
lingua['selectChooseStudents-EN'] = "Choose all students"

lingua['pressCtrlToChose-PT'] = "Pressione CTRL para selecionar mais de um aluno" 
lingua['pressCtrlToChose-PT-BR'] = "Pressione CTRL para selecionar mais de um aluno"  
lingua['pressCtrlToChose-EN'] = "Press CTRL to select more than one student" 

// Ocorrencias
lingua['occurrences-title-PT'] = "Ocorrências"
lingua['occurrences-title-PT-BR'] = "Ocorrências"
lingua['occurrences-title-EN'] = "Occurrence"
lingua['occurrences-subtitle-PT'] = "Registrar nova ocorrência"
lingua['occurrences-subtitle-PT-BR'] = "Cadastrar nova ocorrência"
lingua['occurrences-subtitle-EN'] = "Register new occurrence"

lingua['holderOccurrenceDesc-PT'] = "Carlos se machucou"
lingua['holderOccurrenceDesc-PT-BR'] = "Carlos se machucou"
lingua['holderOccurrenceDesc-EN'] = "Carl got hurt"

lingua['labelOccurrence-PT'] = "Ocorrência"
lingua['labelOccurrence-PT-BR'] = "Ocorrência"
lingua['labelOccurrence-EN'] = "Occurrence"
lingua['labelphoto-PT'] = "Enviar foto da ocorrência"
lingua['labelphoto-PT-BR'] = "Subir foto da ocorrência"
lingua['labelphoto-EN'] = "Upload photo of the occurrence"

lingua['selectChoseStudent-PT'] = "Selecione um aluno"
lingua['selectChoseStudent-PT-BR'] = "Selecione um aluno"
lingua['selectChoseStudent-EN'] = "Chose a student"

lingua['table-image-PT'] = "Foto"
lingua['table-image-PT-BR'] = "Foto"
lingua['table-image-EN'] = "Image"



export default lingua;