const lingua = {};

lingua['home-title-PT'] = 'Bem vindo!'
lingua['home-title-PT-BR'] = 'Bem vindo!'
lingua['home-title-EN'] = 'Welcome!'
lingua['home-subtitle-PT'] = "Sistema de Gestão Escolar"
lingua['home-subtitle-PT-BR'] = "Sistema de Gestão Escolar"
lingua['home-subtitle-EN'] = "School's management system"
lingua['home-option-EN'] = 'Select a language'
lingua['home-option-PT-BR'] = 'Selecione a linguagem'
lingua['home-option-PT'] = 'Selecione o idioma'
lingua['home-content-PT'] = 'Sistema para gerenciamento escolar desenvolvido para a disciplina de Gestão de Projetos B!'
lingua['home-content-PT-BR'] = 'Sistema de gerenciamento escolar desenvolvido para a disciplina Gestão de Projetos B!'
lingua['home-content-EN'] = "System for school's management developed for the subject Management of Projects B!"
lingua['school-labelname-PT'] = "Nome:"
lingua['school-labelname-PT-BR'] = "Nome:"
lingua['school-labelname-EN'] = "Name:"
lingua['school-labeladdress-PT'] = "Endereço:"
lingua['school-labeladdress-PT-BR'] = "Endereço:"
lingua['school-labeladdress-EN'] = "Address:"
lingua['school-labelphone-PT'] = "Telefone:"
lingua['school-labelphone-PT-BR'] = "Telefone:"
lingua['school-labelphone-EN'] = "Telephone:"
lingua['school-labelprincipal-PT'] = "Diretor:"
lingua['school-labelprincipal-PT-BR'] = "Diretor:"
lingua['school-labelprincipal-EN'] = "Principal:"
lingua['school-name-PT'] = "Digite o nome da escola"
lingua['school-name-PT-BR'] = "Digite o nome da escola"
lingua['school-name-EN'] = "Type the school name"
lingua['school-address-PT'] = "Digite o endereço da escola"
lingua['school-address-PT-BR'] = "Digite o endereço da escola"
lingua['school-address-EN'] = "Type the address of the school"
lingua['school-telephone-PT'] = "Digite o telefone da escola"
lingua['school-telephone-PT-BR'] = "Digite o telefone da escola"
lingua['school-telephone-EN'] = "Type the school's telephone"
lingua['telephone-message-PT'] = "Você deve preencher os dados de telefone no padrão: '+55 (55) 23321-5454'"
lingua['telephone-message-PT-BR'] = "Você deve preencher os dados de telefone no padrão: '+55 (55) 23321-5454'"
lingua['telephone-message-EN'] = "You must type the telephone in the format: '+55 (55) 23321-5454' "

export default lingua;